name: Zip and Publish Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Zip Repository
      run: |
        zip -r poppy_garden.zip .
        
    - name: Check for Existing Tag
      id: check_tag
      run: |
        VERSION=$(date +"%Y-%m-%d")
        if git rev-parse "refs/tags/$VERSION" >/dev/null 2>&1; then
          echo "::set-output name=RELEASE_TAG::$VERSION"
        else
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $VERSION
          git push origin $VERSION
          echo "::set-output name=RELEASE_TAG::$VERSION"
        fi
        
    - name: Get Release Name
      id: get_name
      run: |
        echo "::set-output name=RELEASE_NAME::Release ${{ steps.check_tag.outputs.RELEASE_TAG }}"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.check_tag.outputs.RELEASE_TAG }}
        release_name: ${{ steps.get_name.outputs.RELEASE_NAME }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./poppy_garden.zip
        asset_name: poppy_garden.zip
        asset_content_type: application/zip
        
    - name: Create Latest Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'poppy_garden.zip'
        tag: latest
        name: Latest Release
        token: ${{ secrets.GITHUB_TOKEN }}
